<?php echo $this->doctype(); ?>

<html lang="en">
<meta charset="utf-8">
<?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
?>

<!-- Le styles -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.css')) ?>

<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">


</head>
<body>

<nav class="navbar ">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-2">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar" style="background-color: #0a6ebd"></span>
                <span class="icon-bar" style="background-color: #0a6ebd"></span>
                <span class="icon-bar" style="background-color: #0a6ebd"></span>
            </button>
            <a class="navbar-brand" href="http://zend.local:8080/"><i class="fa fa-book"></i></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
                <li class="active"><a href="http://zend.local:8080/">Главная <span class="sr-only">(current)</span></a>
                </li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown
                        <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Поиск">
                </div>
                <button type="submit" class="btn btn-success">Искать</button>
            </form>
            <form class="navbar-form navbar-left">


                <a target="_blank" href="https://github.com/Rif0-coder" class="btn btn-danger"><i class="fa fa-github">
                        Like me</i>
                </a>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li id="icon"><a href="http://zend.local:8080/users/login"><i class="fa fa-sign-in"> Вход</a></i></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li class="nav-divider"></li>
                <li id="icon"><a href="http://zend.local:8080/users/register"><i class="fa fa-user-plus">
                            Регистрация</i> </a></li>
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
    <?php echo $this->content; ?>

    <footer>
        <p class="text-center animated fadeIn" style="animation-duration: 1s;">&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>

    </footer>
</div> <!-- /container -->
<?php echo $this->inlineScript() ?>

</body>
</html>
