<link rel="stylesheet" href="css/animate.css">
<script src="js/jquery.min.js" type="text/javascript"></script>
<script src="js/typed.js" type="text/javascript"></script>
<script>
    $(function () {
        $("#typed").typed({
            stringsElement: $('#typed-strings'),
            loop: true,
        });
    });
</script>
<section id="top">
    <div class="jumbotron text-center has-pattern ">
        <h1>BookAcademy - найдем всё!</h1>
        <div id="typed-strings">
            <p <strong id="normal">Добро пожаловать на сайт</strong> <strong id="big">BookAcademy</strong></p>
        </div>
        <span id="typed"></span>
        <span id="typed"></span>
    </div>
</section>
<div class="container-fluid">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center">Зачем нужен этот сервис?</h3>
            </div>
            <div class="panel-body">
                <p>С помощью нашего онлайн сервиса вы можете выполнить поиск по методической литературе, загруженной
                    преподавателем.
                    <br> Вы вводите текст, а наш сервис оперативно проверяет информацию и выдаёт совпадения.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center">Экономим ваше время</h3>
            </div>
            <div class="panel-body">
                <p>Теперь не нужно судорожно гуглить!
                    <br> Вы сможете ответить так, <strike>как это хочет услышать </strike> как это рассказывал ваш
                    преподаватель.</p>
                <br>
                <br>

            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title text-center">Повысим успеваемость</h3>
            </div>
            <div class="panel-body">
                <p>Что с успеваемостью - неуспеваю успевать.Теперь вы будите получать только хорошие оценки</p>
            </div>
        </div>
    </div>
</div>
<hr>
<!-- /-->
<div class="container-fluid">
    <div class="col-md-12">
        <h2 class="text-center">Как это работает?</h2>
        <h6 class="text-center">Как это работает?</h6>
        <div class="col-sm-4 col-md-4 column text-center">
            <!-- #1 -->
        <span class="fa-stack fa-lg">
        <i class="fa fa-circle fa-stack-2x"></i>
        <i class="fa fa-flag fa-stack-1x fa-inverse"></i>
        </span>
            <h3>Регистрируйтесь и авторизируйтесь</h3>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo.</p>
            <!-- #2 -->
            <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-file-word-o fa-stack-1x fa-inverse"></i>
            </span>
            <h3>Загружайте литературу</h3>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo.</p>
            <!-- #3 -->
            <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-folder-open-o fa-stack-1x fa-inverse"></i>
            </span>
            <h3>Открывайте доступ к файлам</h3>
            <p>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo.
            </p>


        </div>
        <div class="col-sm-4 col-md-4 column text-center animated infinite pulse">
            <img alt="iPhone" class="img-responsive" src=" img/iPhone.png" width="auto" height="auto">
        </div>
        <div class="col-sm-4 col-md-4 column text-center">
            <!-- #1 -->
           <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-search fa-stack-1x fa-inverse"></i>
            </span>
            <h3>Выполняйте поиск</h3>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo.</p>
            <!-- #2 -->
            <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fa fa-smile-o fa-stack-1x fa-inverse"></i>
            </span>
            <h3>Получайте отличные оценки!</h3>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo.</p>

        </div>
    </div>
</div>
<hr>
<!--О нас говорят /-->
<div class="container-fluid">
    <div class="col-md-12">
        <h2 class="text-center">Нас рекомендуют:</h2>
        <div class="col-md-6">
            <blockquote>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
            </blockquote>
        </div>
        <div class="col-md-6">
            <blockquote class="blockquote-reverse">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
            </blockquote>
        </div>
    </div>
</div>
<hr>
<section id="download">
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column text-center">
                <h2 class="text-center">Готов стать отличником?</h2>
                <p class="lead text-center">Пройдите процедуру регистрации.</p>
            </div>
            <div class="col-md-12 text-center">
                <a target="_blank" href="" class="btn btn-lg btn-lead"><span class="glyphicon glyphicon-user"></span>
                    Зарегистрироваться сейчас </a>
            </div>
        </div>
    </div>
</section>
<hr>






